pybo/models.py
# __init__.py 파일에서 생성한 SQLAlchemy 객체 db 
from pybo import db 


# 질문 모델 
# db.Model 클래스를 상속해서 모델 클래스를 만든다. 
class Question(db.Model) : 
    
    # 모델을 이루는 속성들을 각각 컬럼으로 구현했다. 
    # (컬럼의 데이터 타입, primary_key 여부)를 설정할 수 있다. 
    # nullable도 설정가능(기본값 = false)
    id = db.Column(db.Integer, primary_key = True)
    subject = db.Column(db.String(200), primary_key = False)
    content = db.Column(db.Text(), primary_key = False)
    create_date = db.Column(db.DateTime(), primary_key = False)
    

# 답변 모델

class Answer(db.Model) : 
    
    id = db.Column(db.Integer, primary_key = True)
    
    # Answer 모델에서 Question 모델을 참조하기 위해 추가된 속성값 
    question = db.relationship('Question', backref=db.backref('answer_set'))
    
    # question 객체의 id값을 참조하는 외래키 속성 question_id
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete = 'CASCADE'))
    content = db.Column(db.Text(), primary_key = False)
    create_date = db.Column(db.DateTime(), primary_key = False)

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()
    
# 블루프린트 등록
def create_app() : 
    app = Flask(__name__)
    app.config.from_object(config) # config.py 파일에 작성한 항목을 읽기 위해 추가한 코드 

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models # flask의 migrate 기능을 인식하기 위해 추가된 코드

    # blueprint
    from .views import main_views, question_views, answer_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)
    
    return app

pybo/views/answer_views.py
from datetime import datetime 

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods = ('POST', ))
def create(question_id) : 
    
    question = Question.query.get_or_404(question_id)
    content = request.form['content']
    answer = Answer(content = content, create_date = datetime.now())
    question.answer_set.append(answer)
    db.session.commit()
    
    return redirect(url_for('question.detail', question_id = question_id))

pybo/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo() : 
    return 'Hello, Pybo!'

@bp.route('/')
def index() : 
    
    return redirect(url_for('question._list'))

pybo/views/question_views.py
from flask import Blueprint, render_template

from pybo.models import Question

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list() : 
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list = question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id) : 
    question = Question.query.get_or_404(question_id)
    
    return render_template('question/question_detail.html', question = question)

pybo/templates/question/question_detail.html
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5> {{ question.answer_set|length }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>


<form action = "{{ url_for('answer.create', question_id = question.id)}}" method = "post">
    <textarea name = "content" id = "content" rows = 15></textarea>
    <input type = "submit" value = "답변등록">
</form>

pybo/templates/question/question_list.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}